apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: a-simple-app
  namespace: dev
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: a-simple-app
    weight: 100
  wildcardPolicy: None
