apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB9qLB7eMd7duJ7be8GfQY7+OZDjoFp/6dtnfdHPWp/nd3E5RQQva5wEJi9VFC5WPdQsVyYcmzpI4JUatHYatMmW/scm2H5T8G7VSLG4qrxGSjjKV5P96luSc1sZMeEl5eo2h4UEP6CqUIDYqUCLq8U+Qwakp9EeGBKgkbpBRxg0mqVr/LBS3Yh1YzoCJFAMMIk/UtJPdab5Y9TMyG9ijjiwn5eJHI0yTqDUYoAZJlxet9SuFhpTQ4mTB9kmMVWspA0sz32ZNsVFxyjFwVeTTLXZ/5L8a9QLIFO6a++86Y0MXriKEP/Q1aMJ/SrXBx+YQrLhDmfaBo+3WGC/enS4ThWC/rpBgYfZBAtYTjuWxpSa74QC75Y1+UyVwGW3MY5COYhBOsnWYbfv6AeQemlsMStmaBDOsGWlCOAEry2Cj0q4vsMJKKhoCsO3ZwUovEmL2eog9zBcQSK1WtkvypvSgT9glRg6bMUKLPQmiP9fH6Qsemx6tlSmuERQixzRJM0Nd42ZaCew7pkGuvkZdc0yfY0HhEOelmZ8fr+vv7JatXLb74G5XYfw1/CpymOceDxV25Osyx+HjXVlhmP9AnAOL6jttIpdUNQSDu4MGSO4H+ly3CwoitIzMDlwD7P3MvdZ2FSJTVYlyFg5sNOzEu7VmBj6WbvK+QTh9AD77JD0yXpKNerMQeba8LrxiM845GPDCLorCz9mXAG6z6iFeyDIeu0b4U6Lg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
