apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-a-simple-app
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB8yVhPvOZ+Yp21QbZ02ys7+LoTLdi/Tv7dq/WdCiegxJCNK9b/B0x0abp5gTGNdKsqHY3LcIe2hkKBfoPBrjfXcn7wYaFy/f4i8u8sYUK0MNFbahpBzZ4gDEKXAzBlRAgea2ORNZH/DZSZh74t2B3fM34//IsOtOsRZf3zMNMnZApgYl/nZVMhZ+eDJx07q2O9vkS+I7nqPjDSynXo8BTOmJnw2G+5BQKDZsCCto5jrSwbRvPcQEMabfAP2CpUC9bXsZKzmInj/VhdnlLf4RbdHh43ZYUjrKzk5f9YrbFEN+EiPy1DSTNCeCz9b5mO0YO0msRKKlIJXeL4STCmEoGeRCjM2cqRDkuZ5r8tMJj6FEwR5bVWUnBaQzQYdQHkYC2JyX5QW8yBQumBENRH39w/6igmOUpaiEbPlPSYIOuceUN9QB0s+Xz7VwJ/xYSyoa+ABdcSDPcBaMoFXNc+pJvTqymrDwncRL8Rhn5MbQU+A33YTOTXqwhKCVvTm1PjPri3zGyfvdqYrRuBFrXBF0XnzCKA344bme9ywrXg5kXbrklHab8dHu0pi5appKCpo8/MtMVChNsCaMBJZRd363sYKDuwo89tNLfGnHhc5kS/UXbHxGbY24oje+0V3E+qk/zNweOtarA4f6jsZS0rFz/oBLLREIaRdFiVj3D9fY+x9CdERmDKJ7IxO+SF+g7GVWBvF7EJgnMD3xnnNyZ3jM/llDJi6w==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-a-simple-app
      namespace: cicd
    type: Opaque
