apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/jduimovich/asp-gitops.git?ref=HEAD
  creationTimestamp: null
  name: stage
spec: {}
status: {}
